# Generated by Django 6.0.5 on 2026-05-25 19:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('assets', '0002_initial'),
        ('teams', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='asset',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assets', to='teams.organization'),
        ),
        migrations.AddField(
            model_name='asset',
            name='uploaded_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='uploaded_assets', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='assetcomment',
            name='asset',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='assets.asset'),
        ),
        migrations.AddField(
            model_name='assetcomment',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='asset_comments', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='assetcomment',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='replies', to='assets.assetcomment'),
        ),
        migrations.AddField(
            model_name='assetfolder',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='assetfolder',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='asset_folders', to='teams.organization'),
        ),
        migrations.AddField(
            model_name='assetfolder',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='assets.assetfolder'),
        ),
        migrations.AddField(
            model_name='asset',
            name='folder',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assets', to='assets.assetfolder'),
        ),
        migrations.AddField(
            model_name='assetversion',
            name='asset',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='versions', to='assets.asset'),
        ),
        migrations.AddField(
            model_name='assetversion',
            name='uploaded_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='asset',
            index=models.Index(fields=['organization', 'asset_type'], name='assets_asse_organiz_2c4606_idx'),
        ),
        migrations.AddIndex(
            model_name='asset',
            index=models.Index(fields=['organization', 'status'], name='assets_asse_organiz_ad90f0_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='assetversion',
            unique_together={('asset', 'version_number')},
        ),
    ]
