services:
  cwserever:
    build: .
    container_name: cwserver
    ports:
      - "8000:8000"
    volumes:
      - .:/app
      - media_data:/app/media
    depends_on:
      - cwredis
      - cwdb
    env_file:
      - .env
    environment:
      REDIS_HOST: cwredis
      REDIS_PORT: 6379
      DJANGO_SETTINGS_MODULE: cwconfigs.settings
    networks:
      - system
    # Use daphne for ASGI (WebSocket support)
    command: daphne -b 0.0.0.0 -p 8000 cwconfigs.asgi:application

  cwcelery:
    build: .
    container_name: cwcelery
    volumes:
      - .:/app
      - media_data:/app/media
    depends_on:
      - cwredis
      - cwdb
    env_file:
      - .env
    environment:
      REDIS_HOST: cwredis
      REDIS_PORT: 6379
      DJANGO_SETTINGS_MODULE: cwconfigs.settings
    networks:
      - system
    command: celery -A cwconfigs worker -l info --concurrency=2

  cwredis:
    image: redis:7-alpine
    container_name: redis_server
    ports:
      - "6379:6379"
    networks:
      - system

  cwdb:
    image: postgres:15 
    container_name: cwpgdb
    restart: always
    environment:
      POSTGRES_DB: cwdb
      POSTGRES_USER: cwadmin
      POSTGRES_PASSWORD: cw123456
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - system

networks:
  system:

volumes:
  postgres_data:
  media_data: