# Generated by Django 6.0.5 on 2026-05-25 19:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('campaigns', '0001_initial'),
        ('teams', '0001_initial'),
        ('workflows', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='campaign',
            name='client',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='client_campaigns', to='teams.organization'),
        ),
        migrations.AddField(
            model_name='campaign',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_campaigns', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='campaign',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='campaigns', to='teams.organization'),
        ),
        migrations.AddField(
            model_name='campaign',
            name='workflow',
            field=models.ForeignKey(blank=True, help_text='Workflow template attached to this campaign', null=True, on_delete=django.db.models.deletion.SET_NULL, to='workflows.workflowtemplate'),
        ),
        migrations.AddField(
            model_name='campaigndeliverable',
            name='assigned_to',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_deliverables', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='campaigndeliverable',
            name='campaign',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deliverables', to='campaigns.campaign'),
        ),
        migrations.AddField(
            model_name='campaignstage',
            name='assigned_team',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='teams.team'),
        ),
        migrations.AddField(
            model_name='campaignstage',
            name='assigned_to',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_stages', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='campaignstage',
            name='campaign',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stages', to='campaigns.campaign'),
        ),
        migrations.AddField(
            model_name='campaigndeliverable',
            name='stage',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='deliverables', to='campaigns.campaignstage'),
        ),
        migrations.AlterUniqueTogether(
            name='campaignstage',
            unique_together={('campaign', 'order')},
        ),
    ]
