# Generated by Django 6.0.5 on 2026-05-25 19:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('teams', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Presence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('online', 'Online'), ('away', 'Away'), ('busy', 'Do Not Disturb'), ('offline', 'Offline')], default='offline', max_length=20)),
                ('current_resource_type', models.CharField(blank=True, max_length=50)),
                ('current_resource_id', models.PositiveIntegerField(blank=True, null=True)),
                ('last_seen', models.DateTimeField(auto_now=True)),
                ('organization', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='teams.organization')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='presence', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(help_text='Verb: created, updated, deleted, approved, rejected, commented, etc.', max_length=50)),
                ('resource_type', models.CharField(help_text='e.g. campaign, asset, workflow', max_length=50)),
                ('resource_id', models.PositiveIntegerField()),
                ('resource_title', models.CharField(blank=True, max_length=255)),
                ('details', models.JSONField(blank=True, default=dict, help_text='Extra context')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='activities', to=settings.AUTH_USER_MODEL)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activities', to='teams.organization')),
            ],
            options={
                'verbose_name_plural': 'activities',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['organization', 'resource_type', 'resource_id'], name='collaborati_organiz_bdac7d_idx'), models.Index(fields=['organization', '-created_at'], name='collaborati_organiz_351c57_idx')],
            },
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('resource_type', models.CharField(max_length=50)),
                ('resource_id', models.PositiveIntegerField()),
                ('content', models.TextField()),
                ('is_edited', models.BooleanField(default=False)),
                ('is_pinned', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to=settings.AUTH_USER_MODEL)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='teams.organization')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='replies', to='collaboration.comment')),
            ],
            options={
                'ordering': ['created_at'],
                'indexes': [models.Index(fields=['resource_type', 'resource_id'], name='collaborati_resourc_1b4274_idx')],
            },
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notification_type', models.CharField(choices=[('approval_requested', 'Approval Requested'), ('approval_decided', 'Approval Decision'), ('comment_added', 'New Comment'), ('mention', 'Mentioned'), ('assignment', 'Task Assigned'), ('status_change', 'Status Changed'), ('invitation', 'Invitation'), ('deadline', 'Deadline Reminder'), ('system', 'System')], max_length=50)),
                ('title', models.CharField(max_length=255)),
                ('message', models.TextField(blank=True)),
                ('resource_type', models.CharField(blank=True, max_length=50)),
                ('resource_id', models.PositiveIntegerField(blank=True, null=True)),
                ('is_read', models.BooleanField(default=False)),
                ('read_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='triggered_notifications', to=settings.AUTH_USER_MODEL)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='teams.organization')),
                ('recipient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['recipient', 'is_read', '-created_at'], name='collaborati_recipie_9095d3_idx')],
            },
        ),
    ]
