# Generated by Django 6.0.5 on 2026-05-25 19:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AIAgentProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('role', models.CharField(choices=[('writer', 'Creative Copywriter / Scriptwriter'), ('reviewer', 'Brand Safety / Style Guide Auditor'), ('seo', 'SEO & Audience Targeting Expert'), ('designer', 'Visual Concept & Thumbnail Strategist')], max_length=30)),
                ('system_prompt', models.TextField(help_text='Define the expertise, instructions, and rules for this agent.')),
                ('temperature', models.FloatField(default=0.7)),
                ('is_default', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['role', 'name'],
            },
        ),
        migrations.CreateModel(
            name='AIKnowledgeDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('content', models.TextField(help_text='Raw guideline document or reference text.')),
                ('category', models.CharField(choices=[('brand_voice', 'Brand Voice & Tone'), ('style_guide', 'Style & Format Book'), ('analytics', 'Audience Analytics & Key Metrics'), ('reference', 'General Reference Guidelines')], default='brand_voice', max_length=30)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AIPipelineRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('inputs', models.JSONField(blank=True, default=dict, help_text="Execution inputs e.g. {'topic': '...', 'audience': '...'}")),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AIPipelineStep',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('step_type', models.CharField(choices=[('script_generation', 'AI Script / Content Generation'), ('brand_voice_check', 'AI Brand Voice & Guidelines Auditor'), ('thumbnail_concept', 'AI Thumbnail Strategist & Concept Generator'), ('seo_optimization', 'AI SEO & Hashtag Optimization')], max_length=40)),
                ('order', models.PositiveIntegerField()),
                ('prompt_template', models.TextField(help_text='Prompt instructions with optional placeholders like {topic}, {audience}.')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='AIPipelineTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('description', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='AIStepRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('agent_thoughts', models.TextField(blank=True, help_text="Detailed trace logs of the agent's thought process, steps, and intermediate decisions.")),
                ('output_content', models.TextField(blank=True, help_text='Markdown output produced by the agent step.')),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'ordering': ['step__order'],
            },
        ),
    ]
