# Generated by Django 6.0.5 on 2026-05-25 19:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai_workflows', '0001_initial'),
        ('assets', '0002_initial'),
        ('campaigns', '0001_initial'),
        ('teams', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='aiagentprofile',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ai_agents', to='teams.organization'),
        ),
        migrations.AddField(
            model_name='aiknowledgedocument',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ai_knowledge_docs', to='teams.organization'),
        ),
        migrations.AddField(
            model_name='aipipelinerun',
            name='asset',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ai_runs', to='assets.asset'),
        ),
        migrations.AddField(
            model_name='aipipelinerun',
            name='campaign',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ai_runs', to='campaigns.campaign'),
        ),
        migrations.AddField(
            model_name='aipipelinerun',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ai_pipeline_runs', to='teams.organization'),
        ),
        migrations.AddField(
            model_name='aipipelinerun',
            name='triggered_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='aipipelinestep',
            name='agent',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='pipeline_steps', to='ai_workflows.aiagentprofile'),
        ),
        migrations.AddField(
            model_name='aipipelinetemplate',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ai_pipeline_templates', to='teams.organization'),
        ),
        migrations.AddField(
            model_name='aipipelinestep',
            name='template',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='steps', to='ai_workflows.aipipelinetemplate'),
        ),
        migrations.AddField(
            model_name='aipipelinerun',
            name='template',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='runs', to='ai_workflows.aipipelinetemplate'),
        ),
        migrations.AddField(
            model_name='aisteprun',
            name='pipeline_run',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='step_runs', to='ai_workflows.aipipelinerun'),
        ),
        migrations.AddField(
            model_name='aisteprun',
            name='step',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='step_runs', to='ai_workflows.aipipelinestep'),
        ),
        migrations.AlterUniqueTogether(
            name='aipipelinestep',
            unique_together={('template', 'order')},
        ),
    ]
