# Generated by Django 6.0.5 on 2026-05-25 20:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai_workflows', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aipipelinerun',
            name='status',
            field=models.CharField(choices=[('idle', 'Idle / Draft'), ('pending', 'Pending'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('failed', 'Failed')], default='idle', max_length=20),
        ),
    ]
